### ISSUE TITLE
What is PSNR error exactly?

### ISSUE THREAD

**Issue by AdarshMJ** [dyelax/Adversarial_Video_Generation#28]
I know PSNR is Peak signal to Noise Ratio and higher PSNR value implies better the image generated. Is PSNR error and PSNR same? Or am I missing something?

**Comment by dyelax** [comment]
Yep, the function `psnr_error` in `Code/utils.py` just computes regular Peak Signal to Noise Ratio. Sorry for the confusing wording!

**Comment by AdarshMJ** [comment]
Thank you for clarifying this. I wanted to know whether its possible to calculate the AUC for the classifier?

**Comment by dyelax** [comment]
As of right now I don't have code in this project to compute the AUC. But if it's something you want, feel free to implement it and submit a PR!
