### ISSUE TITLE
Can you share the code that generates the gif  file?

### ISSUE THREAD

**Issue by c1a1o1** [dyelax/Adversarial_Video_Generation#29]
Can you share the code that generates the gif  file?

**Comment by dyelax** [comment]
Hi @c1a1o1. Unfortunately, I no longer have the script that I used to create the gifs, but I remember I used ImageMagik to do it, as in this SO answer: https://askubuntu.com/a/648245/628033

**Comment by c1a1o1** [comment]
Thank you very much!
